# Generated by Django 4.2.7 on 2025-09-17 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='acquired_from',
            field=models.ForeignKey(blank=True, help_text='Solo si fue parte de pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones_acquired', to='inventory.customer', verbose_name='Cliente que entregó'),
        ),
        migrations.AddField(
            model_name='phone',
            name='acquisition_type',
            field=models.CharField(blank=True, choices=[('mayorista', 'Compra mayorista'), ('parte_pago', 'Parte de pago'), ('', 'No aplica')], default='', max_length=20, verbose_name='Tipo de adquisición'),
        ),
        migrations.AddField(
            model_name='phone',
            name='battery_percentage',
            field=models.PositiveIntegerField(default=100, verbose_name='Porcentaje de batería'),
        ),
        migrations.AddField(
            model_name='phone',
            name='internal_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código interno'),
        ),
    ]
