# Generated by Django 4.2.7 on 2025-10-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_phone_acquired_from_phone_acquisition_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('available', 'Stock'), ('reserved', 'Reservado'), ('sold', 'Vendido'), ('service', 'Servicio técnico'), ('in_transit', 'En camino'), ('warehouse', 'Depósito')], default='available', max_length=20, verbose_name='Estado'),
        ),
    ]
