# Generated by Django 4.2.7 on 2025-10-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_phone_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodel',
            name='base_price',
        ),
    ]
